// Generated by https://quicktype.io

export interface IUsuarios {
    ok:      boolean;
    msg:     string;
    cliente: Cliente[];
}

export interface Cliente {
    id_cli:    number;
    dni_cli:   number;
    nom_cli:   string;
    ape_cli:   string;
    direc_cli: string;
    tel_cli:   number;
    email_cli: string;
}
